export type IGameProvider = {
  id?: string | number;
  name?: string;
  name_en?: string;
  logo?: string;
  created_at?: number;
  updated_at?: number;
  api_url?: string;
  allow_currencies?: string;
};

export type IGame = {
  id?: number;
  game_provider?: string;
  game_id?: string;
  game_name?: string;
  game_code?: string;
  currency?: string;
  tags?: string;
  game_info?: string;
  stakes?: string;
  rtp?: string;
  max_win?: string;
  image?: string;
  status?: number;
  release_status?: number;
  is_support_free_game?: number;
  category?: number;
  created_at?: number;
  updated_at?: number;
  popular?: number;
  game_type?: string;
  seq?: number;
  is_support_demo_game?: number;
  user_count?: number;
  use_count_day?: number;
  is_tournament?: number;
  game_type_1?: string;
  game_type_2?: string;
  type_id?: number;
  error?: string;
  is_hedging?: number;
  default_currency?: string;
  game_currency?: string;
};

export type IGameLegalBetAmounts = {
  gameId: number;
  gameTypeId: number;
  legalBetAmounts: IGameLegalBetAmount[];
};

export type IGameLegalBetAmount = {
  coinSize: number;
  betMultiplier: number;
  baseBet: number;
  betAmount: number;
};


export type INewestGameOrder = {
  id: string;
  game_provider_id: number;
  game_id: string;
  team_id: number;
  user_id: number;
  currency: string;
  amount: string;
  number: string;
  status: number;
  handle_status: number;
  bet_id: string;
  parent_bet_id: string;
  created_at: number;
  updated_at: number;
  bet_type: string;
  game_transaction_id: string;
  bet_amount: string;
  win_amount: string;
  token: string;
  request_id: string;
  order_time: number;
  other_data: string;
  real_currency: string;
  real_bet_amount: string;
  real_win_amount: string;
  is_big_win: number;
  game_name: string;
  nickname: string;
  game_provider: string;
  game_type_id: number;
  game_code: string;
  game_type_1: string;
  game_type_2: string;
};


export type IGreatestGameOrder = {
  id: number;
  game_provide_id: number;
  game_id: string;
  team_id: number;
  user_id: number;
  currency: string;
  amount: string;
  number: string;
  status: number;
  handle_status: number;
  bet_id: string;
  parent_bet_id: string;
  created_at: number;
  updated_at: number;
  bet_type: string;
  game_transaction_id: string;
  bet_amount: string;
  win_amount: string;
  token: string;
  request_id: string;
  order_time: number;
  other_data: string;
  real_currency: string;
  real_bet_amount: string;
  real_win_amount: string;
  is_big_win: number;
  game_name: string;
  nickname: string;
  game_provider: string;
  times: string;
  game_code: string;
  game_primary_id: number;
  image: string;
  game_type_2: string;
  avatar: string | null;
};


export type ITournamentGameOrder = {
  id: number;
  game_provide_id: number;
  game_id: string;
  team_id: number;
  user_id: number;
  currency: string;
  amount: string;
  number: string;
  status: number;
  handle_status: number;
  bet_id: string;
  parent_bet_id: string;
  created_at: number;
  updated_at: number;
  bet_type: string;
  game_transaction_id: string;
  bet_amount: string;
  win_amount: string;
  token: string;
  request_id: string;
  order_time: number;
  other_data: string;
  real_currency: string;
  real_bet_amount: string;
  real_win_amount: string;
  is_big_win: number;
  game_name: string;
  nickname: string;
  is_tournament: number;
};

export type IBigWin = {
  id: number;
  game_provide_id: number;
  game_id: string;
  team_id: number;
  user_id: number;
  currency: string;
  amount: string;
  number: string;
  status: number;
  handle_status: number;
  bet_id: string;
  parent_bet_id: string;
  created_at: number;
  updated_at: number;
  bet_type: string;
  game_transaction_id: string;
  bet_amount: string;
  win_amount: string;
  token: string;
  request_id: string;
  order_time: number;
  other_data: string;
  real_currency: string;
  real_bet_amount: string;
  real_win_amount: string;
  is_big_win: number;
  game_name: string;
  nickname: string;
  is_tournament: number;
};
