export type IMyBets = {
    id: number;
    game_provide_id: number;
    game_id: string;
    team_id: number;
    user_id: number;
    currency: string;
    amount: string;
    number: string;
    status: number;
    handle_status: number;
    bet_id: string;
    parent_bet_id: string;
    created_at: number;
    updated_at: number;
    bet_type: string;
    game_transaction_id: string;
    bet_amount: string;
    win_amount: string;
    token: string;
    request_id: string;
    order_time: number;
    other_data: string;
    real_currency: string;
    real_bet_amount: string;
    real_win_amount: string;
    is_big_win: number;
    game_name: string | null;
    nickname: string | null;
    game_provider: string;
};
