export const currencySymbol = [
  { code: 'AED', currency: 'UAE Dirham', symbol: 'د.إ' },
  { code: 'ARS', currency: 'Argentine Peso', symbol: '$' },
  { code: 'AUD', currency: 'Australian Dollar', symbol: '$' },
  { code: 'BDT', currency: 'Bangladeshi Taka', symbol: '৳' },
  { code: 'BRL', currency: 'Brazilian Real', symbol: 'R$' },
  { code: 'CAD', currency: 'Canadian Dollar', symbol: '$' },
  { code: 'CHF', currency: 'Swiss Franc', symbol: 'CHF' },
  { code: 'CNY', currency: 'Chinese Yuan', symbol: '¥' },
  { code: 'EGP', currency: 'Egyptian Pound', symbol: '£' },
  { code: 'EUR', currency: 'Euro', symbol: '€' },
  { code: 'GBP', currency: 'British Pound', symbol: '£' },
  { code: 'HKD', currency: 'Hong Kong Dollar', symbol: 'HK$' },
  { code: 'INR', currency: 'Indian Rupee', symbol: '₹' },
  { code: 'IDR', currency: 'Indonesian Rupiah', symbol: 'Rp' },
  { code: 'JPY', currency: 'Japanese Yen', symbol: '¥' },
  { code: 'KRW', currency: 'South Korean Won', symbol: '₩' },
  { code: 'THB', currency: 'Thai Baht', symbol: '฿' },
  { code: 'MNT', currency: 'Mongolian Tögrög', symbol: '₮' },
  { code: 'MXN', currency: 'Mexican Peso', symbol: '$' },
  { code: 'MYR', currency: 'Malaysian Ringgit', symbol: 'RM' },
  { code: 'NZD', currency: 'New Zealand Dollar', symbol: '$' },
  { code: 'PHP', currency: 'Philippine Peso', symbol: '₱' },
  { code: 'RUB', currency: 'Russian Ruble', symbol: '₽' },
  { code: 'TRY', currency: 'Turkish Lira', symbol: '₺' },
  { code: 'USD', currency: 'US Dollar', symbol: '$' },
  { code: 'VND', currency: 'Vietnamese Dong', symbol: '₫' }
];
