export const mockGameProviders: any[] = [
  {
    id: '1',
    name: 'PGSoft',
    image: '/_mock/images/game-provider/6.png',
  },
  {
    id: '2',
    name: 'Pragmatic Play',
    image: '/_mock/images/game-provider/1.png',
  },
  {
    id: '3',
    name: 'Evolution Gaming',
    image: '/_mock/images/game-provider/2.png',
  },
  {
    id: '4',
    name: 'Microgaming',
    image: '/_mock/images/game-provider/3.png',
  },
  {
    id: '5',
    name: 'Playtech',
    image: '/_mock/images/game-provider/4.png',
  },
  {
    id: '6',
    name: 'Betsoft',
    image: '/_mock/images/game-provider/5.png',
  },
  {
    id: '7',
    name: 'Red Tiger',
    image: '/_mock/images/game-provider/6.png',
  },
];

export const mockGameCategories: { id: string; name: string }[] = [
  {
    id: '1',
    name: 'All',
  },
  {
    id: '2',
    name: 'Slots',
  },
  {
    id: '3',
    name: 'Table Games',
  },
  {
    id: '4',
    name: 'Live Casino',
  },
  {
    id: '5',
    name: 'Jackpot',
  },
  {
    id: '6',
    name: 'Other',
  },
];

export const mockGameGames: any[] = [
  {
    id: '1',
    name: 'Fortune Tiger',
    image: '/_mock/images/game/pg/1.png',
    provider: mockGameProviders[0],
    category: mockGameCategories[0].name,
    onlinePlayers: 2222,
    tags: ['Easy', 'Fun', 'High'],
  },
  {
    id: '2',
    name: 'Fortune Mouse',
    image: '/_mock/images/game/pg/2.png',
    provider: mockGameProviders[0],
    category: mockGameCategories[0].name,
    onlinePlayers: 67,
    tags: ['Animals', 'Sample', 'Fun'],
  },
  {
    id: '3',
    name: 'Fortune Rabbit',
    image: '/_mock/images/game/pg/3.png',
    provider: mockGameProviders[0],
    category: mockGameCategories[0].name,
    onlinePlayers: 44,
    tags: ['Slots', 'Sample', 'Fun'],
  },
  {
    id: '4',
    name: 'Wild Ape',
    image: '/_mock/images/game/pg/4.png',
    provider: mockGameProviders[0],
    category: mockGameCategories[0].name,
    onlinePlayers: 28,
    tags: ['Animals', 'Sample', 'Fun'],
  },
  {
    id: '5',
    name: 'Symbols Egypt',
    image: '/_mock/images/game/pg/5.png',
    provider: mockGameProviders[0],
    category: mockGameCategories[0].name,
    onlinePlayers: 90,
    tags: ['Animals', 'Sample', 'Fun'],
  },
  {
    id: '6',
    name: 'Oriental Prosperity',
    image: '/_mock/images/game/pg/6.png',
    provider: mockGameProviders[0],
    category: mockGameCategories[0].name,
    onlinePlayers: 21,
    tags: ['Animals', 'Sample', 'Fun'],
  },
  {
    id: '7',
    name: 'Mask Carnival',
    image: '/_mock/images/game/pg/7.png',
    provider: mockGameProviders[0],
    category: mockGameCategories[0].name,
    onlinePlayers: 2,
    tags: ['Animals', 'Sample', 'Fun'],
  },
  {
    id: '8',
    name: 'Captains Bounty',
    image: '/_mock/images/game/pg/8.png',
    provider: mockGameProviders[0],
    category: mockGameCategories[0].name,
    onlinePlayers: 87,
    tags: ['Animals', 'Sample', 'Fun'],
  },
  {
    id: '9',
    name: 'Yakuza Honor',
    image: '/_mock/images/game/pg/9.png',
    provider: mockGameProviders[0],
    category: mockGameCategories[0].name,
    onlinePlayers: 42,
    tags: ['Animals', 'Sample', 'Fun'],
  },
  {
    id: '10',
    name: 'Bihini',
    image: '/_mock/images/game/pg/10.png',
    provider: mockGameProviders[0],
    category: mockGameCategories[0].name,
    onlinePlayers: 21,
    tags: ['Animals', 'Sample', 'Fun'],
  },
  {
    id: '11',
    name: 'Werewolf Hunt',
    image: '/_mock/images/game/pg/11.png',
    provider: mockGameProviders[1],
    category: mockGameCategories[0].name,
    onlinePlayers: 1,
    tags: ['Animals', 'Sample', 'Fun'],
  },
  {
    id: '12',
    name: 'Mahjong Ways',
    image: '/_mock/images/game/pg/12.png',
    provider: mockGameProviders[1],
    category: mockGameCategories[0].name,
    onlinePlayers: 0,
    tags: ['Animals', 'Sample', 'Fun'],
  },
  {
    id: '13',
    name: 'Chicky Run',
    image: '/_mock/images/game/pg/13.png',
    provider: mockGameProviders[1],
    category: mockGameCategories[0].name,
    onlinePlayers: 666,
    tags: ['Animals', 'Sample', 'Fun'],
  },
  {
    id: '14',
    name: 'Caishen Wins',
    image: '/_mock/images/game/pg/14.png',
    provider: mockGameProviders[1],
    category: mockGameCategories[0].name,
    onlinePlayers: 213,
    tags: ['Animals', 'Sample', 'Fun'],
  },
  {
    id: '15',
    name: 'Piggy Gold',
    image: '/_mock/images/game/pg/15.png',
    provider: mockGameProviders[1],
    category: mockGameCategories[0].name,
    onlinePlayers: 2,
    tags: ['Animals', 'Sample', 'Fun'],
  },
  {
    id: '16',
    name: 'Treasures of Aztec',
    image: '/_mock/images/game/pg/16.png',
    provider: mockGameProviders[1],
    category: mockGameCategories[0].name,
    onlinePlayers: 3,
    tags: ['Animals', 'Sample', 'Fun'],
  },
];
